### ISSUE TITLE
Route not found if app is exported

### ISSUE THREAD

**Issue by gerhardwannemacher** [waynepennington/aurelia-keycloak#2]
When I run my aurelia-app with gulp serve or watch, the all is ok. When I export the app with gulp export, then I get the error after redirect from keycloak: ERROR [app-router] Error: Route not found: /state=....

**Comment by waynepennington** [comment]
Not sure.  Can you provide more info?  On the surface, it seems either your app can't find the redirected route or that an incorrect redirect is sent back by keycloak.  Another idea is that something isn't getting bundled in your export.  keycloak.json? When you exported, did you use a different server? Change the keycloak redirect location?  Using CORS?

**Comment by waynepennington** [comment]
Issue not replicated.  No reports of similar issues.  Therefore, closed.
