### ISSUE TITLE
Injection question

### ISSUE THREAD

**Issue by wshayes** [waynepennington/aurelia-keycloak#4]
You don't add AuthService to the constructor (e.g. `constructor(customerService, dialogs, ea)` of the class as seen below.  Why?  Also, can we highlight this in the help documentation as I've spent a lot of time today because I didn't pay close enough attention to that.  BTW - thank you VERY much for wrapping keycloak.js! 

`import {CustomerService} from 'backend/customer-service';
import {CommonDialogs} from 'resources/dialogs/common-dialogs';
import {EventAggregator} from 'aurelia-event-aggregator';
import {inject} from 'aurelia-framework';

@inject(CustomerService, CommonDialogs, EventAggregator)
export class CustomerEditScreen {
  constructor(customerService, dialogs, ea) {
    this.customerService = customerService;
    this.dialogs = dialogs;
    this.ea = ea;
    this.customer = null;
  }
`

**Comment by waynepennington** [comment]
Well, it's been a while!  Sorry about that.  The AuthService is a singleton and doesn't need to be injected.  I find typical injection to be a necessary evil from time to time but avoid it when I can.  I've been making some local upgrades on this utility and will post in the near future.
